// apps/documentation/src/stories/components/header/pre-configured/samples/alternate-links-react.sample.ts
import { useEffect } from 'react';
import { useLocation } from 'react-router-dom';

export function useAlternateLinks() {
  const { pathname } = useLocation();

  useEffect(() => {
    // Always update related <link rel="alternate" hreflang="..." href="..."> elements, after every route change.
    // You can use the header config, to find the language codes applied to the header switch, if needed.
  }, [pathname]);
}

// apps/documentation/src/stories/components/header/pre-configured/samples/alternate-links-angular.sample.ts
import { Component } from '@angular/core';
import { NavigationEnd, Router } from '@angular/router';
import { filter } from 'rxjs/operators';

@Component({ selector: 'app-root', templateUrl: './app.component.html' })
export class AppComponent {
  constructor(private router: Router) {
    this.router.events
      .pipe(filter(event => event instanceof NavigationEnd))
      .subscribe((event: NavigationEnd) => {
        // Always update related <link rel="alternate" hreflang="..." href="..."> elements, after every route change.
        // You can use the header config, to find the language codes applied to the language switch, if needed.
      });
  }
}
